spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect